### ISSUE TITLE
Make inside Swell is giving error

### ISSUE THREAD

**Issue by toolkiz** [justinfrankel/WDL#23]
`In file included from swell.h:54,
                 from swell-miscdlg-generic.cpp:30:
swell-miscdlg-generic.cpp: In function ‘LRESULT swellFileSelectProc(HWND, UINT, WPARAM, LPARAM)’:
swell-types.h:94:31: error: value computed is not used [-Werror=unused-value]
   94 | #define CreateDirectory(x,y) (!mkdir((x),0755))
      |                              ~^~~~~~~~~~~~~~~~~
swell-miscdlg-generic.cpp:855:22: note: in expansion of macro ‘CreateDirectory’
  855 |                      CreateDirectory(buf,NULL);
      |                      ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: swell-miscdlg-generic.o] Error 1`

**Comment by cfillion** [comment]
`make ALLOW_WARNINGS=1` (in addition to `PRELOAD_GDK=1` and other options you might want like `DEBUG_INFO=1`)

**Comment by toolkiz** [comment]
Thanks. I actually changed the code to pass a void return, and also there was a problem with the dangling pointer, hence I made a dynamic pointer for this case. 

I will take a note of your suggestion and try it out for my next installation

**Comment by toolkiz** [comment]
Thanks. I actually changed the code to pass a void return, and also there was a problem with the dangling pointer, hence I made a dynamic pointer for this case.

I will take a note of your suggestion and try it out for my next installation
