### ISSUE TITLE
[GDK2] swell-generic-gdk.cpp build error

### ISSUE THREAD

**Issue by biopsin** [justinfrankel/WDL#7]
Hi,
seems I'm hitting a issue with gdk2

> g++ -pipe -fvisibility=hidden -fno-math-errno -fPIC -DPIC -Wall -Wshadow -Wno-unused-function -Wno-multichar -Wno-unused-result -Werror -Wno-deprecated-declarations -O2 -DNDEBUG -s -DSWELL_TARGET_GDK=2 -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DSWELL_LICE_GDI -DSWELL_FREETYPE -I/usr/include/freetype2 -I/usr/include/libpng16      -c -o swell-generic-gdk.o swell-generic-gdk.cpp
> swell-generic-gdk.cpp: In function 'HWND__* SWELL_CreateXBridgeWindow(HWND, void**, RECT*)':
>
> swell-generic-gdk.cpp:2002:33: error: 'gdk_x11_window_get_xid' was not declared in this scope
>
>    Window w = XCreateWindow(disp,gdk_x11_window_get_xid(ospar),0,0,r->right-r->left,r->bottom-r->top,0,CopyFromParent, InputOutput, CopyFromParent, 0, NULL);
>                                  ^~~~~~~~~~~~~~~~~~~~~~
> swell-generic-gdk.cpp:2002:33: note: suggested alternative: 'gdk_window_get_width'
>    Window w = XCreateWindow(disp,gdk_x11_window_get_xid(ospar),0,0,r->right-r->left,r->bottom-r->top,0,CopyFromParent, InputOutput, CopyFromParent, 0, NULL);
>                                  ^~~~~~~~~~~~~~~~~~~~~~
>                                  gdk_window_get_width
> make: *** [<builtin>: swell-generic-gdk.o] Error 1

**Comment by veto-gh** [comment]
Iirc you you can also use the [GDK_WINDOW_XID() macro](https://developer.gnome.org/gdk3/stable/gdk3-X-Window-System-Interaction.html#GDK-WINDOW-XID:CAPS) instead of of 'gdk_x11_window_get_xid() to get the xwindow ID.

**Comment by biopsin** [comment]
do you mean [gdk2](https://developer.gnome.org/gdk2/2.24/gdk2-X-Window-System-Interaction.html#GDK-WINDOW-XID:CAPS), I'm no programmer, but it seems to me 'gdk_x11_window_get_xid() is implemented and gdk3 spesific?

**Comment by veto-gh** [comment]
If you replace "gdk_x11_window_get_xid" to "GDK_WINDOW_XID" in swell-generic-gdk.cpp it will work.

**Comment by biopsin** [comment]
Nice, thanks!
